In [1]:
import numpy as np
from numpy.linalg import svd

np.random.seed(121)
a = np.random.randn(4,4)
print(np.round(a,3))

[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]


U,Sigma,Vt 도출

In [3]:
U,Sigma,Vt = svd(a)
print(U.shape,Sigma.shape,Vt.shape)
print("U : \n",np.round(U,3))
print("Sigma Value \n",np.round(Sigma,3))
print("V transpose matrix :\n",np.round(Vt,3))

(4, 4) (4,) (4, 4)
U : 
 [[-0.079 -0.318  0.867  0.376]
 [ 0.383  0.787  0.12   0.469]
 [ 0.656  0.022  0.357 -0.664]
 [ 0.645 -0.529 -0.328  0.444]]
Sigma Value 
 [3.423 2.023 0.463 0.079]
V transpose matrix :
 [[ 0.041  0.224  0.786 -0.574]
 [-0.2    0.562  0.37   0.712]
 [-0.778  0.395 -0.333 -0.357]
 [-0.593 -0.692  0.366  0.189]]


Sigma를 다시 0을 포함한 대칭행렬로 반환

In [5]:
sigma_mat = np.diag(Sigma)
a_ = np.dot(np.dot(U,sigma_mat),Vt)
print(np.round(a_,3))

[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]


데이터 로우 간 의존성이 있을 경우

In [6]:
a[2] = a[0]+a[1]
a[3] = a[0]
print(np.round(a,3))

[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.542  0.899  1.041 -0.073]
 [-0.212 -0.285 -0.574 -0.44 ]]


다시 SVD 수행해 Sigma 값 확인

In [7]:
U,Sigma,Vt = svd(a)
print(U.shape,Sigma.shape,Vt.shape)
print("Sigma Value : \n",np.round(Sigma,3))

(4, 4) (4,) (4, 4)
Sigma Value : 
 [2.663 0.807 0.    0.   ]


In [8]:
#U 행렬은 Sigma와 내적을 수행하므로 Sigma의 앞 2행에 대응되는 열만 추출
U_=U[:,:2]
Sigma_ = np.diag(Sigma[:2])

#V전치 행렬은 앞2행만 추출
Vt_ = Vt[:2]
print(U_.shape,Sigma_.shape,Vt_.shape)

#U,Sigma,Vt의 내적을 수행하며 다시 원본 행렬 복원
a_ = np.dot(np.dot(U_,Sigma_),Vt_)
print(np.round(a_,3))

(4, 2) (2, 2) (2, 4)
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.542  0.899  1.041 -0.073]
 [-0.212 -0.285 -0.574 -0.44 ]]
